DROP TABLE IF EXISTS users, categories, event_states, locations, events,
    event_request_stats, event_requests, compilations, compilations_events, event_admin_comments;

CREATE table IF NOT EXISTS users(
    user_id bigint generated by default as identity primary key,
    name varchar(64) NOT NULL,
    email varchar(64) NOT NULL
);
CREATE unique index if not exists email_uindex ON users (email);

CREATE table IF NOT EXISTS categories(
    category_id bigint generated by default as identity primary key,
    name varchar(64) NOT NULL
);
CREATE unique index if not exists name_uindex ON categories (name);

CREATE table IF NOT EXISTS event_states(
    state_id bigint generated by default as identity primary key,
    name varchar(64) NOT NULL unique
);
CREATE unique index if not exists name_uindex ON event_states (name);

CREATE table IF NOT EXISTS locations(
    location_id bigint generated by default as identity primary key,
    lat float NOT NULL,
    lon float NOT NULL
);

CREATE table IF NOT EXISTS events(
    event_id bigint generated by default as identity primary key,
    annotation varchar(512) NOT NULL,
    category_id bigint REFERENCES categories (category_id) ON DELETE CASCADE,
    created_on timestamp without time zone,
    description varchar NOT NULL,
    event_date timestamp without time zone NOT NULL,
    initiator_id bigint REFERENCES users (user_id) ON DELETE CASCADE,
    location_id bigint REFERENCES locations (location_id) ON DELETE CASCADE,
    paid bool NOT NULL,
    participant_limit int NOT NULL,
    published_on timestamp without time zone,
    request_moderation bool NOT NULL,
    state_id bigint REFERENCES event_states (state_id) ON DELETE CASCADE,
    title varchar(256) NOT NULL
);

CREATE table IF NOT EXISTS event_request_stats(
    stat_id bigint generated by default as identity primary key,
    name varchar NOT NULL unique
);

CREATE table IF NOT EXISTS event_requests(
    event_requests_id bigint generated by default as identity primary key,
    created timestamp without time zone,
    event_id  bigint REFERENCES events (event_id) ON DELETE CASCADE,
    requester_id bigint REFERENCES users (user_id) ON DELETE CASCADE,
    status_id bigint REFERENCES event_request_stats (stat_id) ON DELETE CASCADE
);

CREATE table IF NOT EXISTS compilations(
    compilation_id bigint generated by default as identity primary key,
    pinned bool NOT NULL,
    title varchar(256) NOT NULL
);

CREATE table IF NOT EXISTS compilations_events(
    compilation_id bigint REFERENCES compilations (compilation_id) ON DELETE CASCADE,
    event_id bigint REFERENCES events (event_id) ON DELETE CASCADE,
    PRIMARY KEY (compilation_id, event_id)
);

CREATE table IF NOT EXISTS event_admin_comments(
    admin_comment_id bigint generated by default as identity primary key,
    created timestamp without time zone,
    event_id  bigint REFERENCES events (event_id) ON DELETE CASCADE,
    text varchar NOT NULL
);


















