DROP TABLE IF EXISTS users, categories, event_states, locations, events;

CREATE table IF NOT EXISTS users(
    user_id bigint generated by default as identity primary key,
    name varchar NOT NULL,
    email varchar NOT NULL
);
CREATE unique index if not exists email_uindex ON users (email);

CREATE table IF NOT EXISTS categories(
    category_id bigint generated by default as identity primary key,
    name varchar NOT NULL
);
CREATE unique index if not exists name_uindex ON categories (name);

CREATE table IF NOT EXISTS event_states(
    state_id bigint generated by default as identity primary key,
    name varchar NOT NULL unique
);
CREATE unique index if not exists name_uindex ON event_states (name);

CREATE table IF NOT EXISTS locations(
    location_id bigint generated by default as identity primary key,
    lat float NOT NULL,
    lon float NOT NULL
);

CREATE table IF NOT EXISTS events(
    event_id bigint generated by default as identity primary key,
    annotation varchar NOT NULL,
    category_id bigint REFERENCES categories (category_id) ON DELETE CASCADE,
    confirmed_requests bigint,
    created_on timestamp without time zone,
    description varchar NOT NULL,
    event_date timestamp without time zone NOT NULL,
    initiator_id bigint REFERENCES users (user_id) ON DELETE CASCADE,
    location_id bigint REFERENCES locations (location_id) ON DELETE CASCADE,
    paid bool NOT NULL,
    participant_limit int NOT NULL,
    published_on timestamp without time zone,
    request_moderation bool NOT NULL,
    state_id bigint REFERENCES event_states (state_id) ON DELETE CASCADE,
    title varchar NOT NULL,
    views int NOT NULL
);



















