DROP TABLE IF EXISTS hits;

CREATE table IF NOT EXISTS hits(
    hit_id bigint generated by default as identity primary key,
    app varchar NOT NULL,
    uri varchar NOT NULL,
    ip varchar NOT NULL,
    timestamp timestamp NOT NULL
);